version: "2"
services:
  app:
    container_name: matic
    restart: on-failure
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb:/data/db/
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
volumes:
  mongodb:
  redis: